// Copyright (c) 2018 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m3db/m3ninx/util/types.go

package util

import (
	"reflect"

	"github.com/golang/mock/gomock"
)

// MockRefCount is a mock of RefCount interface
type MockRefCount struct {
	ctrl     *gomock.Controller
	recorder *MockRefCountMockRecorder
}

// MockRefCountMockRecorder is the mock recorder for MockRefCount
type MockRefCountMockRecorder struct {
	mock *MockRefCount
}

// NewMockRefCount creates a new mock instance
func NewMockRefCount(ctrl *gomock.Controller) *MockRefCount {
	mock := &MockRefCount{ctrl: ctrl}
	mock.recorder = &MockRefCountMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockRefCount) EXPECT() *MockRefCountMockRecorder {
	return _m.recorder
}

// IncRef mocks base method
func (_m *MockRefCount) IncRef() {
	_m.ctrl.Call(_m, "IncRef")
}

// IncRef indicates an expected call of IncRef
func (_mr *MockRefCountMockRecorder) IncRef() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IncRef", reflect.TypeOf((*MockRefCount)(nil).IncRef))
}

// DecRef mocks base method
func (_m *MockRefCount) DecRef() {
	_m.ctrl.Call(_m, "DecRef")
}

// DecRef indicates an expected call of DecRef
func (_mr *MockRefCountMockRecorder) DecRef() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DecRef", reflect.TypeOf((*MockRefCount)(nil).DecRef))
}

// MoveRef mocks base method
func (_m *MockRefCount) MoveRef() {
	_m.ctrl.Call(_m, "MoveRef")
}

// MoveRef indicates an expected call of MoveRef
func (_mr *MockRefCountMockRecorder) MoveRef() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "MoveRef", reflect.TypeOf((*MockRefCount)(nil).MoveRef))
}

// NumRef mocks base method
func (_m *MockRefCount) NumRef() int {
	ret := _m.ctrl.Call(_m, "NumRef")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumRef indicates an expected call of NumRef
func (_mr *MockRefCountMockRecorder) NumRef() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NumRef", reflect.TypeOf((*MockRefCount)(nil).NumRef))
}
